export enum FirebaseAuthErrors {
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  USER_DISABLED = 'USER_DISABLED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EMAIL_EXISTS = 'EMAIL_EXISTS',
  TOO_MANY_ATTEMPTS_TRY_LATER = 'TOO_MANY_ATTEMPTS_TRY_LATER',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND',
}
